# Generated by Django 3.1.3 on 2021-06-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications_Reciver', '0002_auto_20210619_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default='metio', max_length=100),
            preserve_default=False,
        ),
    ]
